---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ir
spec:
  tls:
    - hosts:
      - {{ .Values.INGRESS_FQDN }}
      secretName: {{ .Values.TLS_SECRET_NAME }}
  rules:
    - host: {{ .Values.INGRESS_FQDN }}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ .Release.Name }}-svc
            servicePort: 80