apiVersion: v1
kind: Service
metadata:
  name: intelowl-uwsgi-svc
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: {{ .Values.NGINX_SERVICE_TYPE }}
---
apiVersion: v1
kind: Service
metadata:
  name: backend-rabbitmq
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  labels:
    app: {{ .Release.Name }}
spec:
  
  ports:
   - port: {{ .Values.DB_PORT }}
  selector:
   app: postgres